accounts/urls.py
from django.contrib import admin
from django.urls import path , include , reverse_lazy , re_path
from .views import *
from django.contrib.auth import views as auth_views


app_name = 'accounts'
urlpatterns = [
    #path('register/activate/<uidb64>/<token>/',user_activation_view , name = 'activate'),
    path('register/',RegisterView.as_view(),name = 'register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'accounts/registration/login.html' , redirect_authenticated_user = True),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'accounts/registration/logged_out.html'),name = 'logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(
                                            template_name ='accounts/registration/password_reset.html',
                                            email_template_name = 'accounts/registration/password_reset_email.html',
                                            success_url='done/'),
                            name='password_reset'),

    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(
                                            template_name ='accounts/registration/password_reset_done.html'),
                            name='password_reset_done'),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
                                            template_name ='accounts/registration/password_reset_confirm.html',
                                            success_url ='done/'),
                            name='password_reset_confirm'),

    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(
                                            template_name ='accounts/registration/password_reset_complete.html'),
                            name='password_reset_complete'),


]

home/urls.py
from django.contrib import admin
from django.urls import path , include

from .views import *

app_name = 'home'
urlpatterns = [
    path('',Index.as_view(),name = 'posts'),
    #path('home/post/<int:id>/',postDetails.as_view(),name = 'post')
    
]

paysera/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns
from .views import *
from profiles.views import *

urlpatterns = []

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('dash_board/<str:notification>/<str:action>/<int:pk>/',dash_board_ajax),
    path('dash_board/',dash_board_view , name = "dash_board"),
    path('',include('home.urls',namespace = 'home')),
    path('accounts/',include('accounts.urls' , namespace = 'accounts')),
    path('profiles/',include('profiles.urls',namespace = 'profiles')),
    path('offers/',include('offers.urls',namespace = 'offers')),
    path('notification/',include('notifications.urls',namespace = 'notifications')),
    path('oauth/', include('social_django.urls', namespace = 'social')),

)

profiles/urls.py
from django.urls import path , include,re_path , reverse
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'profiles'

urlpatterns = [
    path('<str:username>/',profile_view,name = 'profile'),
    path('<username>/password_set/',password_set_view , name = 'password_set'),
    path('<str:username>/password_change/',
            auth_views.PasswordChangeView.as_view(template_name = "profiles/changePassword.html",
                success_url ='done/'),
                                name='password_change'),

    path('<str:username>/password_change/done/',
            auth_views.PasswordChangeDoneView.as_view(template_name = "profiles/changePasswordDone.html") ,
                                                name='password_change_done'),
    path('<username>/delete/',profile_delete_view_ajax,name = 'profile_delete_ajax'),
    path('<username>/edit/',profile_edit_view_ajax,name = 'profile_edit_ajax'),
    path('<username>/data/<data>/',profile_view_ajax , name = 'profile_data_ajax'),



]

paysera/views.py
from django.shortcuts import render , redirect
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from accounts.models import *
from offers.models import *
from notifications.models import *
# Create your views here.



def dash_board_view(request):
    offers = Notification.objects.filter(msg=None).count()
    messages = Notification.objects.filter(notif=None).count()
    if offers > 0 :
        offers = Notification.objects.filter(msg=None).order_by('-date')
    else:
        offers = None
    if messages > 0 :
        messages = Notification.objects.filter(notif=None).order_by('-date')
    else:
        messages = None

    return render(request,"paysera/dash_board.html",{"offers" : offers , "messages" : messages })

@login_required
@require_POST
def dash_board_ajax(request,notification,action,pk):
    if request.method == "POST" and request.is_ajax() and request.user.is_superuser:
        if action == "remove":
            if notification == "offer":
                Offer.objects.get(pk = pk).delete()
            else:
                Message.objects.get(pk = pk).delete()
        elif action == "check":
            if notification == "offer":
                offer = Offer.objects.get(pk = pk)
                offer.notification.seen = True
                offer.save()
            else:
                message = Message.objects.get(pk = pk)
                message.notification.seen = True
                message.save()
        else:
            if notification == "offer":
                offer = Offer.objects.get(pk = pk)
                offer.notification.seen = False
                offer.save()
            else:
                message = Message.objects.get(pk = pk)
                message.notification.seen = False
                message.save()
        return JsonResponse({ "data":"operation done"},status=200)
    else:
        return redirect("home:posts")

paysera/templates/base.html
{% load i18n  %}
{% load staticfiles %}
<!doctype html>
<html >


  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=320, height=device-height, target-densitydpi=medium-dpi" />
    <link rel="stylesheet" href="{% static "/home/base.css" %}">
    <link rel="stylesheet" type="text/css" href=" {% static "/frameworks/semantic/semantic.min.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block picker %}{% endblock picker %}
    <!-- each child template css -->
    {% block css %}{% endblock css %}
    <!-- each child template title -->
      <link rel="stylesheet" href="{% static "login/css/style.css" %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <a class="navbar-brand" href="{% url "home:posts" %}" id="home"><i class="black tie icon"></i>PayDz</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Offers" %}</a>
        <div class="dropdown-menu item" aria-labelledby="navbarDropdown">
          {% if user.is_authenticated and user.profile.profileComplete == True %}
            <a class="dropdown-item item" data-toggle="modal" data-target="#buy"  id="buyOffer" href="#"><i class="cc visa icon"></i>{% trans "Buy" %}</a>
            <hr>
            <a class="dropdown-item item" data-toggle="modal" data-target="#sell"  id="sellOffer" href="#"><i class="money bill alternate icon"></i>{% trans "Sell" %}</a>
          {% elif user.is_authenticated and user.profile.profileComplete == False %}
          <a class="dropdown-item item"  href="{% url "profiles:password_set" user.username %}"><i class="cc visa icon"></i>{% trans "Buy" %}</a>
          <hr>
          <a class="dropdown-item item"  href="{% url "profiles:password_set" user.username %}"><i class="money bill alternate icon"></i>{% trans "Sell" %}</a>
          {% else %}
          <a class="dropdown-item item"  href="{% url "accounts:login" %}"><i class="cc visa icon"></i>{% trans "Buy" %}</a>
          <hr>
          <a class="dropdown-item item"  href="{% url "accounts:login" %}"><i class="money bill alternate icon"></i>{% trans "Sell" %}</a>
          {% endif %}

        </div>
      </li>
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle " href="#" id="moreId" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "More" %}</a>
      <div class="dropdown-menu item" aria-labelledby="navbarDropdown">
        {% if user.is_authenticated %}
          <a class="dropdown-item item" data-toggle="modal" data-target="#contanct"  id="contanctId" href="#"><i class="question circle icon"></i>{% trans "Contact Us" %}</a>
        {% else %}
        <a class="dropdown-item item"  href="{% url "accounts:login" %}"><i class="question circle icon"></i>{% trans "Contact Us" %}</a>
        {% endif %}
        <hr>
          <a class="dropdown-item item" data-toggle="modal" data-target="#about"  id="aboutId" href="#"><i class="users icon"></i>{% trans "About Us" %}</a>
      </div>
    </li>

    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="lanId" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% trans "Language" %}
      </a>
      <div class="dropdown-menu item" aria-labelledby="navbarDropdown">
        <a href="/fr/" class="dropdown-item item"><i class="france flag"></i>  {% trans "French" %}</a>
        <a href="/en/" class="dropdown-item item"><i class="us flag"></i> {% trans "English" %}</a>
      </div>
      </li>

      </ul>

      <br>


      <ul class="navbar-nav ml-auto">

      {% if user.is_superuser %}
      <li class="nav-item dropdown" >
        <a class="nav-link notif" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <p id="notifCount"></p><i class="bell icon"></i>
        </a>
        <div class="dropdown-menu item scrollable-menu" id="notifId" aria-labelledby="navbarDropdown">

        </div>

      </li>
      <li class="nav-item dropdown" >
        <a class="nav-link notif" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <p id="msgCount"></p><i class="comment icon"></i>
        </a>
          <div class="dropdown-menu item scrollable-menu" id="msgId" aria-labelledby="navbarDropdown">

          </div>
      </li>
      {% endif %}

      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="registerId" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% if user.is_authenticated %}
          <img class="ui avatar image" src="{% static "/images/user.png" %}"> {{user.username}}
        {% else %}
        <i class="user icon"></i>{% trans "Registration" %}
        {% endif %}
      </a>
      <div class="dropdown-menu item" aria-labelledby="navbarDropdown">
        {% if user.is_superuser %}
        <a href="{% url "dash_board" %}" class="dropdown-item item">{% trans "Dash Board" %}</a>
        <hr>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url "profiles:profile" user.username %}" class="dropdown-item item">{% trans "Settings" %}</a>
            <hr>
            <a href="{% url "accounts:logout" %}" class="dropdown-item item">{% trans "Logout" %}</a>
        {% else %}
            <a href="{% url "accounts:login" %}" class="dropdown-item item">{% trans "Login" %}</a>
            <hr>
            <a href="{% url "accounts:register" %}" class="dropdown-item item">{% trans "Register" %}</a>
        {% endif %}
      </div>

      </li>
    </ul>

  </div>
  </nav>

  <!-- for bootstrap modals -->
  {% include "./offers/modals.html" %}






 <div id="main">
  {% block content %}
  {% endblock %}
</div>


      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>







      <script src="{% static "/offers/offer.js" %}"></script>
      <script src="{% static "/frameworks/semantic/semantic.min.js" %}"></script>

      <script type="text/javascript">

        /*{% if user.is_superuser %}
            var username = $("#username").val();
            var url = "ws://" + window.location.host + "/ws/notification/"+ username + "/";
            socket = new WebSocket(url);

            socket.onmessage = function(event){
              var data = JSON.parse(event.data);
              if(data.type == "message"){
                var messageCount = document.getElementById("msgCount");
                if( data.count > 0 ){
                  messageCount.innerHTML = data.count;
                  var msgId = document.getElementById("msgId");
                  msgId.innerHTML = "";
                  for(var i = 0 ; i < data.count ; i++){
                    var anchor = document.createElement("a");
                    var hr = document.createElement("hr");
                    anchor.className = "dropdown-item item";
                    anchor.setAttribute("href","url");
                    anchor.textContent = data.content[i].username;
                    msgId.appendChild(anchor);
                    msgId.appendChild(hr);
                  }
                }

              }
              else if(data.type == "notification"){
                var notificationCount = document.getElementById("notifCount");
                if(data.count > 0 ){
                  notificationCount.innerHTML = data.count;
                  var notifId = document.getElementById("notifId");
                  notifId.innerHTML = "";
                  for(var i = 0 ; i < data.count ; i++){
                    var anchor = document.createElement("a");
                    var hr = document.createElement("hr");
                    anchor.className = "dropdown-item item";
                    anchor.setAttribute("href","url");
                    anchor.textContent = data.content[i].username;
                    notifId.appendChild(anchor);
                    notifId.appendChild(hr);
                  }
                }
              }
              else if(data.type == "no notifications"){
                var notificationCount = document.getElementById("notifCount");
                notificationCount.innerHTML = "";
              }
              else{
                var messageCount = document.getElementById("msgCount");
                messageCount.innerHTML = "";
              }

              //console.log(data.type , data.count  , data.content[data.count-1])
            }
            socket.onclose = function(event){
              console.log("connection closed.");
            };
        {% endif %}
    */


      </script>


    <!-- each child template js -->
    {% block js %}{% endblock js %}



  </body>
</html>